
import './globals.css'
import { Inter } from 'next/font/google'
import { StyledEngineProvider } from "@mui/material/styles";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledEngineProvider injectFirst>
      <body className={inter.className}>{children}</body>

      </StyledEngineProvider>
    </html>
  )
}
